#!/bin/bash

# ═══════════════════════════════════════════════════════════════
# Copilot Environment Setup Script
# ═══════════════════════════════════════════════════════════════
# This script helps set up the .env file for GitHub Copilot when
# starting a new chat session. It reads from GitHub Secrets or
# can accept environment variables directly.
#
# Usage:
#   ./scripts/copilot-env-setup.sh
#
# Or with environment variables:
#   BASE_RPC_URL="https://..." WALLET_PRIVATE_KEY="0x..." ./scripts/copilot-env-setup.sh
#
# This script is safe to commit - it contains NO secrets, only
# the structure for creating the .env file.
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env"

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Copilot Environment Setup${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠️  .env file already exists${NC}"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}Keeping existing .env file${NC}"
        exit 0
    fi
fi

# Function to prompt for variable if not set
get_var() {
    local var_name="$1"
    local description="$2"
    local default_value="${3:-}"
    local is_secret="${4:-false}"
    
    # Check if already set in environment
    local current_value="${!var_name:-}"
    
    if [ -n "$current_value" ]; then
        echo -e "${GREEN}✓${NC} $var_name (from environment)"
        echo "$current_value"
        return
    fi
    
    # Prompt user
    echo -e "${YELLOW}$description${NC}"
    if [ "$is_secret" = "true" ]; then
        read -s -p "$var_name: " value
        echo ""
    else
        if [ -n "$default_value" ]; then
            read -p "$var_name [$default_value]: " value
            value="${value:-$default_value}"
        else
            read -p "$var_name: " value
        fi
    fi
    
    echo "$value"
}

echo -e "${BLUE}Please provide the following configuration values:${NC}"
echo -e "${YELLOW}(Press Enter to use default values where available)${NC}"
echo ""

# Collect configuration
echo -e "\n${BLUE}━━━ Network Configuration ━━━${NC}"
CHAIN_ID=$(get_var "CHAIN_ID" "Chain ID (8453=Base, 1=Ethereum)" "8453")
BASE_RPC_URL=$(get_var "BASE_RPC_URL" "Base RPC URL (e.g., https://base-mainnet.g.alchemy.com/v2/YOUR-KEY)")
ETHEREUM_RPC_URL=$(get_var "ETHEREUM_RPC_URL" "Ethereum RPC URL (optional, press Enter to skip)" "")

echo -e "\n${BLUE}━━━ Wallet Configuration ━━━${NC}"
WALLET_PRIVATE_KEY=$(get_var "WALLET_PRIVATE_KEY" "Wallet Private Key (with 0x prefix)" "" "true")

echo -e "\n${BLUE}━━━ Bot Configuration ━━━${NC}"
DRY_RUN=$(get_var "DRY_RUN" "Dry Run Mode (true/false)" "true")
SCAN_INTERVAL=$(get_var "SCAN_INTERVAL" "Scan Interval in ms" "1000")
MIN_PROFIT_PERCENT=$(get_var "MIN_PROFIT_PERCENT" "Minimum Profit %" "0.5")

echo -e "\n${BLUE}━━━ Contract Addresses (Optional) ━━━${NC}"
FLASHSWAP_V2_ADDRESS=$(get_var "FLASHSWAP_V2_ADDRESS" "FlashSwap V2 Contract Address" "")
FLASHSWAP_V2_OWNER=$(get_var "FLASHSWAP_V2_OWNER" "FlashSwap V2 Owner Address" "")

echo -e "\n${BLUE}━━━ Phase 3 AI Configuration ━━━${NC}"
PHASE3_AI_ENABLED=$(get_var "PHASE3_AI_ENABLED" "Enable Phase 3 AI" "true")
PHASE3_SECURITY_ENABLED=$(get_var "PHASE3_SECURITY_ENABLED" "Enable Phase 3 Security" "false")
PHASE3_CROSSCHAIN_ENABLED=$(get_var "PHASE3_CROSSCHAIN_ENABLED" "Enable Cross-Chain" "false")

# Create .env file
echo ""
echo -e "${BLUE}Creating .env file...${NC}"

cat > "$ENV_FILE" << EOF
# ═══════════════════════════════════════════════════════════════
# COPILOT-CONSCIOUSNESS ENVIRONMENT CONFIGURATION
# ═══════════════════════════════════════════════════════════════
# Generated by copilot-env-setup.sh on $(date)
# ═══════════════════════════════════════════════════════════════

# ─────────────────────────────────────────────────────────────
# NETWORK CONFIGURATION
# ─────────────────────────────────────────────────────────────
NODE_ENV=development
CHAIN_ID=$CHAIN_ID

# RPC URLs
BASE_RPC_URL=$BASE_RPC_URL
EOF

# Add Ethereum RPC only if provided
if [ -n "$ETHEREUM_RPC_URL" ]; then
    echo "ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL" >> "$ENV_FILE"
fi

cat >> "$ENV_FILE" << EOF

# ─────────────────────────────────────────────────────────────
# WALLET CONFIGURATION
# ─────────────────────────────────────────────────────────────
WALLET_PRIVATE_KEY=$WALLET_PRIVATE_KEY

# ─────────────────────────────────────────────────────────────
# BOT CONFIGURATION
# ─────────────────────────────────────────────────────────────
DRY_RUN=$DRY_RUN
SCAN_INTERVAL=$SCAN_INTERVAL
MIN_PROFIT_PERCENT=$MIN_PROFIT_PERCENT
CONCURRENCY=10
MAX_GAS_PRICE=100
MAX_GAS_COST_PERCENTAGE=40
MIN_PROFIT_THRESHOLD=0.01

# ─────────────────────────────────────────────────────────────
# CONTRACT ADDRESSES
# ─────────────────────────────────────────────────────────────
EOF

if [ -n "$FLASHSWAP_V2_ADDRESS" ]; then
    echo "FLASHSWAP_V2_ADDRESS=$FLASHSWAP_V2_ADDRESS" >> "$ENV_FILE"
fi
if [ -n "$FLASHSWAP_V2_OWNER" ]; then
    echo "FLASHSWAP_V2_OWNER=$FLASHSWAP_V2_OWNER" >> "$ENV_FILE"
fi

cat >> "$ENV_FILE" << EOF

# ─────────────────────────────────────────────────────────────
# PHASE 3 CONFIGURATION
# ─────────────────────────────────────────────────────────────
PHASE3_AI_ENABLED=$PHASE3_AI_ENABLED
PHASE3_SECURITY_ENABLED=$PHASE3_SECURITY_ENABLED
PHASE3_CROSSCHAIN_ENABLED=$PHASE3_CROSSCHAIN_ENABLED

# AI Components
PHASE3_RL_LEARNING_RATE=0.1
PHASE3_RL_DISCOUNT_FACTOR=0.95
PHASE3_RL_EXPLORATION_RATE=0.3
PHASE3_NN_HIDDEN_LAYER_SIZE=16
PHASE3_NN_LEARNING_RATE=0.01
PHASE3_NN_CONFIDENCE=0.7

# Consciousness Settings
PHASE3_EPISODIC_MEMORY=true
PHASE3_MAX_EPISODES=5000
PHASE3_ADVERSARIAL_RECOGNITION=true
PHASE3_SELF_REFLECTION=true
PHASE3_REFLECTION_INTERVAL=3600000
PHASE3_CONSCIOUSNESS_LEARNING_RATE=0.05

# ─────────────────────────────────────────────────────────────
# DASHBOARD / MONITORING
# ─────────────────────────────────────────────────────────────
DISABLE_DASHBOARD=true
HEALTH_CHECK_INTERVAL=30000
EOF

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✓ .env file created successfully!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Review the .env file: cat .env"
echo "  2. Build the project: npm run build"
echo "  3. Run TheWarden: ./TheWarden --stream"
echo ""
