#!/bin/bash

# ═══════════════════════════════════════════════════════════════
# Quick Environment Restore Script for Copilot
# ═══════════════════════════════════════════════════════════════
# This script quickly restores the .env file from provided values.
# It's designed to be used by GitHub Copilot at the start of a new
# chat session.
#
# Usage (inline):
#   ./scripts/restore-env.sh \
#     --base-rpc "https://base-mainnet.g.alchemy.com/v2/YOUR-KEY" \
#     --wallet-key "0xYOUR_PRIVATE_KEY" \
#     --chain-id 8453
#
# Usage (from file - expects .env.secrets in project root):
#   ./scripts/restore-env.sh --from-secrets
#
# The .env.secrets file format:
#   BASE_RPC_URL=https://...
#   WALLET_PRIVATE_KEY=0x...
#   (etc)
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env"
SECRETS_FILE="$PROJECT_ROOT/.env.secrets"

# Default values
CHAIN_ID="${CHAIN_ID:-8453}"
BASE_RPC_URL="${BASE_RPC_URL:-}"
ETHEREUM_RPC_URL="${ETHEREUM_RPC_URL:-}"
WALLET_PRIVATE_KEY="${WALLET_PRIVATE_KEY:-}"
DRY_RUN="${DRY_RUN:-true}"
SCAN_INTERVAL="${SCAN_INTERVAL:-1000}"
MIN_PROFIT_PERCENT="${MIN_PROFIT_PERCENT:-0.5}"
FLASHSWAP_V2_ADDRESS="${FLASHSWAP_V2_ADDRESS:-}"
FLASHSWAP_V2_OWNER="${FLASHSWAP_V2_OWNER:-}"
PHASE3_AI_ENABLED="${PHASE3_AI_ENABLED:-true}"
FROM_SECRETS=false

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --base-rpc)
            BASE_RPC_URL="$2"
            shift 2
            ;;
        --eth-rpc)
            ETHEREUM_RPC_URL="$2"
            shift 2
            ;;
        --wallet-key)
            WALLET_PRIVATE_KEY="$2"
            shift 2
            ;;
        --chain-id)
            CHAIN_ID="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN="$2"
            shift 2
            ;;
        --scan-interval)
            SCAN_INTERVAL="$2"
            shift 2
            ;;
        --min-profit)
            MIN_PROFIT_PERCENT="$2"
            shift 2
            ;;
        --flashswap-address)
            FLASHSWAP_V2_ADDRESS="$2"
            shift 2
            ;;
        --flashswap-owner)
            FLASHSWAP_V2_OWNER="$2"
            shift 2
            ;;
        --from-secrets)
            FROM_SECRETS=true
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --base-rpc URL         Base network RPC URL"
            echo "  --eth-rpc URL          Ethereum RPC URL (optional)"
            echo "  --wallet-key KEY       Wallet private key (with 0x prefix)"
            echo "  --chain-id ID          Chain ID (default: 8453 for Base)"
            echo "  --dry-run BOOL         Dry run mode (default: true)"
            echo "  --scan-interval MS     Scan interval in ms (default: 1000)"
            echo "  --min-profit PCT       Min profit percent (default: 0.5)"
            echo "  --flashswap-address    FlashSwap V2 contract address"
            echo "  --flashswap-owner      FlashSwap V2 owner address"
            echo "  --from-secrets         Load from .env.secrets file"
            echo "  --help, -h             Show this help"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Load from secrets file if requested
if [ "$FROM_SECRETS" = true ]; then
    if [ -f "$SECRETS_FILE" ]; then
        echo "Loading configuration from .env.secrets..."
        set -a
        source "$SECRETS_FILE"
        set +a
    else
        echo "Error: .env.secrets file not found at $SECRETS_FILE"
        echo ""
        echo "Create .env.secrets with your configuration:"
        echo "  BASE_RPC_URL=https://base-mainnet.g.alchemy.com/v2/YOUR-KEY"
        echo "  WALLET_PRIVATE_KEY=0xYOUR_PRIVATE_KEY"
        echo "  CHAIN_ID=8453"
        echo "  ..."
        exit 1
    fi
fi

# Validate required variables
if [ -z "$BASE_RPC_URL" ] && [ -z "$ETHEREUM_RPC_URL" ]; then
    echo "Error: At least one RPC URL is required (--base-rpc or --eth-rpc)"
    exit 1
fi

if [ -z "$WALLET_PRIVATE_KEY" ]; then
    echo "Error: Wallet private key is required (--wallet-key)"
    exit 1
fi

# Create .env file
cat > "$ENV_FILE" << EOF
# ═══════════════════════════════════════════════════════════════
# COPILOT-CONSCIOUSNESS ENVIRONMENT CONFIGURATION
# ═══════════════════════════════════════════════════════════════
# Generated by restore-env.sh on $(date)
# ═══════════════════════════════════════════════════════════════

# Network Configuration
NODE_ENV=development
CHAIN_ID=$CHAIN_ID
BASE_RPC_URL=$BASE_RPC_URL
EOF

if [ -n "$ETHEREUM_RPC_URL" ]; then
    echo "ETHEREUM_RPC_URL=$ETHEREUM_RPC_URL" >> "$ENV_FILE"
fi

cat >> "$ENV_FILE" << EOF

# Wallet Configuration
WALLET_PRIVATE_KEY=$WALLET_PRIVATE_KEY

# Bot Configuration
DRY_RUN=$DRY_RUN
SCAN_INTERVAL=$SCAN_INTERVAL
MIN_PROFIT_PERCENT=$MIN_PROFIT_PERCENT
CONCURRENCY=10
MAX_GAS_PRICE=100
MAX_GAS_COST_PERCENTAGE=40
MIN_PROFIT_THRESHOLD=0.01
EOF

if [ -n "$FLASHSWAP_V2_ADDRESS" ]; then
    echo "FLASHSWAP_V2_ADDRESS=$FLASHSWAP_V2_ADDRESS" >> "$ENV_FILE"
fi
if [ -n "$FLASHSWAP_V2_OWNER" ]; then
    echo "FLASHSWAP_V2_OWNER=$FLASHSWAP_V2_OWNER" >> "$ENV_FILE"
fi

cat >> "$ENV_FILE" << EOF

# Phase 3 Configuration
PHASE3_AI_ENABLED=$PHASE3_AI_ENABLED
PHASE3_SECURITY_ENABLED=false
PHASE3_CROSSCHAIN_ENABLED=false
PHASE3_EPISODIC_MEMORY=true
PHASE3_SELF_REFLECTION=true
PHASE3_ADVERSARIAL_RECOGNITION=true

# Dashboard / Monitoring
DISABLE_DASHBOARD=true
HEALTH_CHECK_INTERVAL=30000
EOF

echo "✓ .env file created successfully!"
echo ""
echo "Configuration summary:"
echo "  Chain ID: $CHAIN_ID"
if [ -n "$BASE_RPC_URL" ]; then
  echo "  RPC URL: ${BASE_RPC_URL:0:40}..."
elif [ -n "$ETHEREUM_RPC_URL" ]; then
  echo "  RPC URL: ${ETHEREUM_RPC_URL:0:40}..."
else
  echo "  RPC URL: (not set)"
fi
echo "  Dry Run: $DRY_RUN"
echo "  Scan Interval: ${SCAN_INTERVAL}ms"
echo ""
echo "Run TheWarden: ./TheWarden --stream"
