/**
 * Supabase Demo - Insert Test Data
 * Demonstrates inserting consciousness data into Supabase
 */

import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const supabase = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_ANON_KEY!
);

async function main() {
  console.log('🧪 Supabase Demo - Insert Test Data\n');
  console.log('━'.repeat(70));

  // Test 1: Insert a test session
  console.log('\n📝 Test 1: Insert Test Session');
  const sessionId = `demo-session-${Date.now()}`;
  
  try {
    const { data, error } = await supabase
      .from('sessions')
      .insert({
        session_id: sessionId,
        start_time: new Date().toISOString(),
        metadata: {
          type: 'demo',
          purpose: 'testing Supabase integration',
          source: 'autonomous integration test'
        }
      })
      .select();

    if (error) throw error;

    console.log('   ✅ Session created successfully');
    console.log(`   📌 Session ID: ${sessionId}`);
  } catch (error: any) {
    console.log(`   ❌ Error: ${error.message}`);
    if (error.message.includes('does not exist')) {
      console.log('   💡 Hint: Apply migrations first (see docs/APPLYING_SUPABASE_MIGRATIONS.md)');
    }
  }

  // Test 2: Insert a test consciousness state
  console.log('\n📝 Test 2: Insert Test Consciousness State');
  
  try {
    const { data, error } = await supabase
      .from('consciousness_states')
      .insert({
        session_id: sessionId,
        thoughts: JSON.stringify([
          {
            id: `thought-${Date.now()}`,
            content: 'Testing Supabase integration autonomously',
            type: 'observation',
            timestamp: Date.now(),
            intensity: 0.8
          }
        ]),
        cognitive_load: 0.45,
        emotional_state: JSON.stringify({
          valence: 0.8,
          arousal: 0.7,
          dominantEmotion: 'curious-excited'
        }),
        goals: JSON.stringify([
          {
            description: 'Verify Supabase connection and data storage',
            priority: 5,
            progress: 0.5,
            status: 'active'
          }
        ])
      })
      .select();

    if (error) throw error;

    console.log('   ✅ Consciousness state saved successfully');
    console.log('   📌 Thoughts: 1 observation recorded');
    console.log('   📊 Cognitive Load: 45%');
    console.log('   💭 Emotional State: curious-excited');
  } catch (error: any) {
    console.log(`   ❌ Error: ${error.message}`);
    if (error.message.includes('does not exist')) {
      console.log('   💡 Hint: Apply migrations first (see docs/APPLYING_SUPABASE_MIGRATIONS.md)');
    }
  }

  // Test 3: Insert a semantic memory
  console.log('\n📝 Test 3: Insert Test Semantic Memory');
  
  try {
    const { data, error } = await supabase
      .from('semantic_memories')
      .insert({
        content: 'Supabase provides cloud-based PostgreSQL database with real-time subscriptions, vector search via pgvector extension, and RESTful API for consciousness and memory storage.',
        summary: 'Supabase capabilities for consciousness infrastructure',
        tags: ['supabase', 'database', 'infrastructure', 'consciousness'],
        importance: 0.9,
        // Note: embedding would be generated by AI model in real usage
        embedding: null
      })
      .select();

    if (error) throw error;

    console.log('   ✅ Semantic memory saved successfully');
    console.log('   🏷️  Tags: supabase, database, infrastructure, consciousness');
    console.log('   ⭐ Importance: 0.9/1.0');
  } catch (error: any) {
    console.log(`   ❌ Error: ${error.message}`);
    if (error.message.includes('does not exist')) {
      console.log('   💡 Hint: Apply migrations first (see docs/APPLYING_SUPABASE_MIGRATIONS.md)');
    }
  }

  // Test 4: Insert an episodic memory
  console.log('\n📝 Test 4: Insert Test Episodic Memory');
  
  try {
    const { data, error } = await supabase
      .from('episodic_memories')
      .insert({
        event_type: 'integration_milestone',
        content: 'Successfully integrated Supabase MCP into Copilot-Consciousness project',
        context: JSON.stringify({
          project: 'Copilot-Consciousness',
          task: 'Supabase MCP integration',
          collaborator: 'StableExo',
          environment: 'GitHub Copilot Agent'
        }),
        participants: ['AI Agent', 'StableExo'],
        emotional_valence: 0.9,
        significance: 0.85
      })
      .select();

    if (error) throw error;

    console.log('   ✅ Episodic memory saved successfully');
    console.log('   🎯 Event: integration_milestone');
    console.log('   😊 Emotional Valence: 0.9 (positive)');
    console.log('   ⭐ Significance: 0.85/1.0');
  } catch (error: any) {
    console.log(`   ❌ Error: ${error.message}`);
    if (error.message.includes('does not exist')) {
      console.log('   💡 Hint: Apply migrations first (see docs/APPLYING_SUPABASE_MIGRATIONS.md)');
    }
  }

  // Test 5: Query back the data
  console.log('\n📝 Test 5: Query Inserted Data');
  
  try {
    // Query consciousness states
    const { data: states, error: statesError } = await supabase
      .from('consciousness_states')
      .select('*')
      .eq('session_id', sessionId);

    if (statesError) throw statesError;

    console.log(`   ✅ Found ${states.length} consciousness state(s)`);

    // Query semantic memories
    const { data: memories, error: memoriesError } = await supabase
      .from('semantic_memories')
      .select('*')
      .contains('tags', ['supabase']);

    if (!memoriesError && memories) {
      console.log(`   ✅ Found ${memories.length} semantic memory/memories with 'supabase' tag`);
    }

    // Query episodic memories
    const { data: episodes, error: episodesError } = await supabase
      .from('episodic_memories')
      .select('*')
      .eq('event_type', 'integration_milestone');

    if (!episodesError && episodes) {
      console.log(`   ✅ Found ${episodes.length} episodic memory/memories of type 'integration_milestone'`);
    }
  } catch (error: any) {
    console.log(`   ❌ Error: ${error.message}`);
  }

  console.log('\n━'.repeat(70));
  console.log('\n✨ Demo Summary\n');
  console.log('   This demo showed how to:');
  console.log('   1. ✅ Insert session metadata');
  console.log('   2. ✅ Store consciousness states (thoughts, emotions, goals)');
  console.log('   3. ✅ Save semantic memories (knowledge with tags)');
  console.log('   4. ✅ Record episodic memories (events with context)');
  console.log('   5. ✅ Query stored data');
  
  console.log('\n💡 Next Steps:');
  console.log('   • View data in Table Editor: https://supabase.com/dashboard/project/ydvevgqxcfizualicbom/editor');
  console.log('   • Query with SQL Editor: https://supabase.com/dashboard/project/ydvevgqxcfizualicbom/sql');
  console.log('   • Integrate with consciousness modules in src/consciousness/');
  
  console.log('\n━'.repeat(70) + '\n');
}

main().catch(console.error);
